<?php

namespace AhorroBundle\Repository;

/**
 * AhorroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AhorroRepository extends \Doctrine\ORM\EntityRepository
{
}
