extra:
    resource: "@ExtraBundle/Controller/"
    type:     annotation
    prefix:   /

api_login_check:
    path: /authenticate

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
ingreso:
    type:     rest
    resource: ExtraBundle\Controller\ExtraController
    defaults: {_format: json}

usuario:
    type:     rest
    resource: UsuarioBundle\Controller\UsuarioController
    defaults: {_format: json}
    
evento:
    type:     rest
    resource: EventoBundle\Controller\EventoController
    defaults: {_format: json}
    
cuenta:
    type:     rest
    resource: CuentaBundle\Controller\CuentaController
    defaults: {_format: json}

    
ahorro:
    type:     rest
    resource: AhorroBundle\Controller\AhorroController
    defaults: {_format: json}
