extra:
    resource: "@ExtraBundle/Controller/"
    type:     annotation
    prefix:   /

cuenta:
    resource: "@CuentaBundle/Controller/"
    type:     annotation
    prefix:   /

ahorro:
    resource: "@AhorroBundle/Controller/"
    type:     annotation
    prefix:   /

api_login_check:
    path: /authenticate

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
ingreso:
    type:     rest
    resource: ExtraBundle\Controller\ExtraController
    defaults: {_format: json}

usuario:
    type:     rest
    resource: UsuarioBundle\Controller\UsuarioController
    defaults: {_format: json}
    
evento:
    type:     rest
    resource: EventoBundle\Controller\EventoController
    defaults: {_format: json}

