extra:
    resource: "@ExtraBundle/Controller/"
    type:     annotation
    prefix:   /

cuenta:
    resource: "@CuentaBundle/Controller/"
    type:     annotation
    prefix:   /

ahorro:
    resource: "@AhorroBundle/Controller/"
    type:     annotation
    prefix:   /

evento:
    resource: "@EventoBundle/Controller/"
    type:     annotation
    prefix:   /

api_login_check:
    path: /authenticate

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

usuario:
    type:     rest
    resource: UsuarioBundle\Controller\UsuarioController
    defaults: {_format: json}
