<?php

namespace UsuarioBundle\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{

    public function buscarPorAtributos($username){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('usuario')
                ->from($this->getEntityName(), 'usuario');
        $this->addSearchParameters($qb, $username);
        return $qb->getQuery()->getResult();
    }

    public function addSearchParameters($qb, $username){
        if($username){
            $qb->where($qb->expr()->like('usuario.username', ':username'));
            $qb->setParameter('username', "%{$username}%");
        }
    }

}
