<?php

namespace ExtraBundle\Repository;

/**
 * EgresoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgresoRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarPorAtributos($egreso){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('egreso')
                ->from($this->getEntityName(), 'egreso');
        $this->addSearchParameters($qb, $egreso);
        return $qb->getQuery()->getResult();
    }

    public function addSearchParameters($qb, $egreso){
        if($egreso){
            $qb->where($qb->expr()->like('egreso.username', ':username'));
            $qb->setParameter('username', "%{$egreso}%");
        }
    }
}
